# Generated by Django 5.1.6 on 2025-02-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Side', '0002_registerdb_post_like_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintdB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comp_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Comp_Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Comp_Mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('Comp_Subject', models.CharField(blank=True, max_length=100, null=True)),
                ('Comp_Proof', models.FileField(blank=True, null=True, upload_to='Complaint Proofs')),
                ('Comp_Details', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
