# Generated by Django 5.1.6 on 2025-02-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Side', '0003_complaintdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdb',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/'),
        ),
        migrations.AddField(
            model_name='registerdb',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
