# Generated by Django 5.1.6 on 2025-02-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Side', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdb',
            name='warning_count',
            field=models.IntegerField(default=0),
        ),
    ]
