# Generated by Django 5.1.6 on 2025-03-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Side', '0007_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactdB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Mobile_Number', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Subject', models.CharField(blank=True, max_length=100, null=True)),
                ('Msg', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
