# Generated by Django 5.1.6 on 2025-03-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Side', '0008_contactdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='comment_audios/'),
        ),
    ]
