# Generated by Django 5.1.6 on 2025-03-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Side', '0009_comment_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
